### ISSUE TITLE
Levels are not preserved when plotting

### ISSUE THREAD

**Issue by BlakeList** [queryverse/VegaLite.jl#125] opened 2018-09-24 09:13 UTC
When trying to plot , for example, weather over time using VegaLite, it was noted that the levels were not being kept for the x axis (months). The levels for the months were explicitly stated (using CategoricalArray) however, they were once again not preserved in the actual plotting using VegaLite. Code example has been provided.
[github_issue_levels.zip](https://github.com/fredo-dedup/VegaLite.jl/files/2410253/github_issue_levels.zip)

**Comment by davidanthoff** [comment] 2018-09-26 19:18
Yeah, we don't have any integration with that right now. I need to think a bit how to best do that.

**Comment by jlewis91** [comment] 2021-03-11 20:26
@davidanthoff This is a duplicate of https://github.com/queryverse/VegaLite.jl/issues/335, can be closed?

**Closed** 2021-03-27 01:06 UTC
Labels: enhancement
