### ISSUE TITLE
spec1 + spec2 doesn't make spec1 a layer

### ISSUE THREAD

**Issue by pablosanjose** [queryverse/VegaLite.jl#307] opened 2020-05-12 17:03 UTC
This is perhaps debatable, but it's tripped me seriously when I started using VegaLite. If I do
```
table = [(x=rand(), y1=rand(), y2=rand()) for _ in 1:10]
table |> @vlplot(:line, x = :x, y = :y1) + @vlplot(:line, x = :x, y = :y2)
```
I get a plot with a single curve, that of `(x, y2)`. The reason is that `spec1 + spec2` doesn't move `spec1` into a layer, it just adds `spec2` to a layer, leaving spec1 as parent spec, and resulting in a single-layer plot which renders as a single curve. This is related to #230, and probably also to #303 and #304.

I'm pretty sure  by looking at some of the tests that this behaviour is intended, but for a beginner it is mighty confusing. It took me quite some time to figure out that I was meant to do
```
table |> @vlplot() + @vlplot(:line, x = :x, y = :y1) + @vlplot(:line, x = :x, y = :y2)
```

Is there any reason for this design? What would be the problem if we had `spec1+spec2` be equivalent to the current `@vlplot() + spec1 + spec2`, so that we obtain a two-layer plot with an empty parent spec?

**Comment by davidanthoff** [comment] 2020-06-04 03:06
Yes, this is intentional, and I also agree that it is not good :) The problem is that we do need a way to put things into the parent spec. I'm going to close this as a duplicate of https://github.com/queryverse/VegaLite.jl/issues/230, where I'm trying to come up with a better story for this whole situation.

**Closed by davidanthoff** 2020-06-04 03:06 UTC
