### ISSUE TITLE
Export Vegalite Plot as HTML (including interactivity)

### ISSUE THREAD

**Issue by UsorUsor** [queryverse/VegaLite.jl#198] opened 2019-11-02 17:35 UTC
As requested, the feature request has been added.

**Comment by davidanthoff** [comment] 2019-12-07 00:59
Just a quick update on this: the new Julia 1.3/artifact branch has a new way to generate HTML output, in particular it completely embeds all the vega and vega-lite code inside the HTML, so that these HTML files also work offline. As soon as we have that merged, I'll try to also add support for a simple `plot |> save("foo.html")`, that should be really straightforward at that point.

**Comment by VPetukhov** [comment] 2019-12-29 21:29
Hi @davidanthoff,

Thanks for the amazing library! I'm wondering why you didn't mention that we can do it with the existing functions? Indeed, the following code produce correct interactive html:

```julia
function savehtml(filepath::AbstractString, spec::VegaLite.AbstractVegaSpec)
    tmp_path = VegaLite.getparams(spec) |> JSON.json |> VegaLite.writehtml_full
    return cp(tmp_path, filepath)
end

t_plt = DataFrame(rand(500, 2)) |> @vlplot(x=:x1, y=:x2, mark=:point);
savehtml("t_plt.html", t_plt);
```

Perhaps, the main question here is why `writehtml_full` doesn't accept parameter for the plot path.

Btw, looks like it's a duplicate of https://github.com/queryverse/VegaLite.jl/issues/184

**Closed** 2020-01-01 00:39 UTC
Labels: enhancement
