### ISSUE TITLE
Shape mapping methods silently fail

### ISSUE THREAD

**Issue by jrising** [queryverse/VegaLite.jl#112] opened 2018-06-25 13:02 UTC
The "Choropleth of unemployment rate per county" and "One dot per zipcode in the U.S." example result in a webpage with a blank canvas:
![image](https://user-images.githubusercontent.com/579448/41851481-e8aef78e-787f-11e8-9bdf-5376bfec1a5c.png)

A clue to what's wrong is with the "One dot per airport in the US overlayed on geoshape" which is intended to both draw a map and drop points on top of it.  Only the points appear:
![image](https://user-images.githubusercontent.com/579448/41851533-1a29bcfe-7880-11e8-9acb-f53891d122de.png)

This is after a recent (this morning) `Pkg.update`, and the VegaLite non-mapping examples work fine.

This is a linux install with Julia 0.6.2, VegaLite 0.3.2, and VegaDatasets 0.3.0.

**Comment by davidanthoff** [comment] 2018-07-05 10:30
Is this in jupyter lab? I think there might be some bug in that one... I can now reproduce this to the following extend: on ubuntu in jupyter lab, I also get the map missing. If I then open the same notebook in nteract, everything works. Saving such a plot with ``p |> save("foo.pdf")`` also works correctly.

I'll continue to dig what the root cause is, but would be good to know whether I'm on the right track right now.

**Comment by jrising** [comment] 2018-07-06 10:28
This is from the REPL.  When I do a `@vlplot` command, a browser window pops up, showing the above.  I do get the correct result when I save the plot, so that's great!

**Comment by davidanthoff** [comment] 2018-07-06 11:57
I _think_ this has something to do with same origin policies in browsers... Here is a work around that works in the REPL: Install the [ElectronDisplay.jl](https://github.com/davidanthoff/ElectronDisplay.jl) package, and do a ``using ElectronDisplay`` before you plot. Plots from the REPL will then no longer be shown in the browser, but instead in a custom electron window, and things seem to work there.

We'll still need to find a general solution to this, of course.

**Comment by jrising** [comment] 2018-07-09 11:41
Okay, thanks.  That worked for me.

**Comment by jrising** [comment] 2018-07-09 11:42
Feel free to split off the general problem into a separate issue and we can close this one.

**Comment by davidanthoff** [comment] 2019-12-28 04:55
I'm closing this for now, I'm tracking the proper solution for this in #183. Problem is understood, but solution more complicated than I thought :)

**Closed by davidanthoff** 2019-12-28 04:55 UTC
Labels: bug
